### ISSUE TITLE
Target Shell (HELP) @_@

### ISSUE THREAD

**Issue by Szofiii** [gelstudios/gitfiti#101]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/78085972/194094592-e6af9ccd-47f4-447b-913b-5a286bb17b19.png">
what does this mean? dont know much about shellscripting

**Comment by Necione** [comment]
Just type powershell, and it'll great a PS file which you can then run.

**Comment by gelstudios** [comment]
@Szofiii im going to assume you figured this out. If not, re-open with a description about your operating system + terminal.
