### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by Asday** [gelstudios/gitfiti#104]
I saw this project forever ago, or maybe I saw people writing rude words on their contribution history, I forget.

Anyway, it gave me an idea for a project of my own, the output of which you can see at https://github.com/Asday/eee-mirror if you like, though the important part is [in the contributions](https://github.com/Asday).

Thanks for the inspiration!

**Comment by gelstudios** [comment]
Does your project clone the commit counts? github added a toggle at some point to show private repo contributions on your public profile?

**Comment by gelstudios** [comment]
If you make your project public, add a link to to this one's readme :)
