### ISSUE TITLE
ending script after entering name

### ISSUE THREAD

**Issue by EnderNon** [gelstudios/gitfiti#105]
i entered nothing for the url, then typed in EnderNon for username. script ended. tried lowercase endernon. script still just ends right there

**Comment by MichaelBlm** [comment]
same

**Comment by gelstudios** [comment]
What platform + python version are you running?

**Comment by gelstudios** [comment]
and what happens when it "ends"? no stacktrace?

**Comment by gelstudios** [comment]
It looks like github updated the commit / contributions calendar data source (it was an SVG) and now its a weird all-html format instead.

You can patch / comment that function out, probably needs to yield or return 0 and it will work until I can fix the parser.
