### ISSUE TITLE
404 on /repo//users/username/contributions

### ISSUE THREAD

**Issue by jasonsee** [gelstudios/gitfiti#20]
Looks like maybe Github API has changed recently on the contributions url?

**Comment by gelstudios** [comment]
Maybe, the contributions calendar data url (and format!) has changed a few times. Do you know what the new one is? I can dig into this tonight if not, thanks for the heads up

**Comment by gelstudios** [comment]
Are you using github enterprise? The current url worked and the commit data was parsed correctly from: https://github.com/users/jasonsee/contributions

But that was when accepting the default github base url (press enter at first prompt).

**Comment by jasonsee** [comment]
You are totally correct. I'm not sure what my problem was earlier today - my personal account is not enterprise, but I'm obviously connected to an enterprise account - the repo I was was making wasn't private, however. 

Thanks for looking into it - and making this repo! :+1:
