### ISSUE TITLE
update it!!!

### ISSUE THREAD

**Issue by emcenrue** [gelstudios/gitfiti#23]
It's not working. I changed the urllib2 to urllib, but then I got some reference errors and gave up. I really want to use this 4 da lulz

**Comment by gelstudios** [comment]
reference errors? what os/platform are you using? its possible that the calendar format changed again.

**Comment by gelstudios** [comment]
Appears to be working for me, can you check what version of python you have installed?

**Comment by gelstudios** [comment]
I can't reproduce the error
