### ISSUE TITLE
Clearer template example

### ISSUE THREAD

**Issue by dannyid** [gelstudios/gitfiti#25]
Hey, it's not clear from your example which direction the template array-of-arrays should be going since your example is a square. Perhaps give a non-square example so that it's clear that all the Sundays are in the same array, all the Mondays, etc?

**Comment by dannyid** [comment]
I'm working on this little guy, check it out:

https://gist.github.com/dannyid/dc6993ec0d2755f64ac4

**Comment by gelstudios** [comment]
Cool! Sorry about the less than clear template examples. It is a litte more clear if you look inside `gitfiti.py`. The outer arrays refer to the day of the week, which you can think about it as the vertical positioning of the pixels (Y-axis). Within those day of week arrays, the values refer to the week of year, which are more easily thought of as horizontal positioning (X-axis). The 'hello' example within `gitfiti.py` makes this easy to see.
