### ISSUE TITLE
dont really understand how this works

### ISSUE THREAD

**Issue by wayneiny** [gelstudios/gitfiti#27]
Hi I really appreciate your work and creativity but i am having a hard time running this on my ubuntu. So what I did was I ran the .py and entered the git repo name for gitfiti and it created a .sh. After I ran that shell script, it gives created a new git repository and commit a gitfiti file, which is a large set of number and no file type. Is this gitfiti file the .png of .jpeg pixel picture? Thank you.

**Comment by gelstudios** [comment]
The `gitfiti` file itself is basically junk, and the "picture" is a side effect of the date stamps of the commits to that file. The generated shell script will create a repository, the gitfiti junk file, and all the junk commits necessary to "draw" the pixel art into your commit calendar. Then the script will push those commits to the remote repository on github's server. The script needs to be able to authenticate with github via ssh, which you can test in your console by entering: `ssh git@github.com`

**Comment by SCKelemen** [comment]
I didnt know not understanding how something works was cause for an issue.
