### ISSUE TITLE
I cannot run at right way

### ISSUE THREAD

**Issue by androidmalin** [gelstudios/gitfiti#28]
1.Create a new github repo  [https://github.com/androidmalin/nice](https://github.com/androidmalin/nice)
2.at root of the nice project  run gitfiti.py
3.Run gitfiti.py and follow the prompts for username, art selection, offset, and repo name.
I cannot input what for art selection,offset, and repo name. 
Can you give me a example

![gitfit](https://cloud.githubusercontent.com/assets/5959435/12001095/8850ef92-ab1c-11e5-8f74-9a2dffaae89b.png)

**Comment by strugee** [comment]
Read the prompts. You're putting in `androidmalin` in the prompt where it asks for a GitHub installation URL. And you're putting `nice` in as your username, instead of `androidmalin`.
