### ISSUE TITLE
Can't make light green dot

### ISSUE THREAD

**Issue by retep-mathwizard** [gelstudios/gitfiti#29]
1 gives you the medium colored dot.

**Comment by gelstudios** [comment]
that might be a bug, were you trying to match or exceed your max commits?

**Comment by retep-mathwizard** [comment]
Match. I commited more than my max one day and it turned all the dots back 1 color

**Comment by gelstudios** [comment]
If you committed more than your max, github scales all existing commits to the new maximum.

So if your max was say 10 at the time of gitfiti-ing your account, and then at a later date you commit 12 times, all commits (including gitifi-related ones) would scale too.
