### ISSUE TITLE
New derivative in Bash

### ISSUE THREAD

**Issue by tardypad** [gelstudios/gitfiti#43]
I had trouble with the installation of some of the Python libraries used in some derivatives
and I was missing some features I wanted
ans I guess I was ~~inspired~~ bored
so I made my own derivative fully in Bash :)

Maybe you can list it in your derivatives in case any people might be interested
https://github.com/tardypad/github-jack
Thanks

**Comment by gelstudios** [comment]
added, might have to upstream those sweet space invaders 👍
