### ISSUE TITLE
New GUI to make creating templates easier

### ISSUE THREAD

**Issue by ZachSaucier** [gelstudios/gitfiti#44]
I created [a GUI](https://github.com/ZachSaucier/github-calendar-customizer) ([demo](http://codepen.io/Zeaklous/full/PzVRBy/)) that allows images and pre-made arrays to be used as input. It also has drag-to-edit capabilities like the Gitfiti painter that exists already.

Thanks for the original project!

**Comment by marcofugaro** [comment]
Cool, I made something similar but to work directly on github's webpage, [here it is](https://gist.github.com/marcofugaro/e3d6f154891440629529c910a2798c99)

**Comment by gelstudios** [comment]
This was the nicest GUI gitfiti ever got :)
