### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by J053Fabi0** [gelstudios/gitfiti#46]
Enter GitHub URL (leave blank to use https://github.com/): https://github.com/J053Fabi0
Enter your GitHub username: J053Fabi0
There was a problem fetching data from https://github.com/J053Fabi0users/J053Fabi0/contributions
HTTP Error 404: Not Found

What I did wrong?

**Comment by stuntguy3000** [comment]
Is there a repo there?

**Comment by J053Fabi0** [comment]
Oh, I need to give my repo URL, then my user name?

**Comment by J053Fabi0** [comment]
Like [https://github.com/J053Fabi0/Draw/](url)

**Comment by gelstudios** [comment]
You just need to enter your username: J053Fabi0

It should then get your existing calendar data from a url like: https://github.com/users/J053Fabi0/contributions

a 404 might be happening because github changes the calendar data url from time to time, or theres a bug in gitfiti string handling.

**Comment by gelstudios** [comment]
see issue #41

**Comment by J053Fabi0** [comment]
I did it, thanks. As you can see I write hello. But how can I draw something else?

**Comment by gelstudios** [comment]
If you haven't already tried, you can commit gitfiti into multiple repositories.

OR you can edit the output script accordingly, you should only need to remove the first few and last few lines, basically anything that doesn't start with `GIT_`.
