### ISSUE TITLE
can't get images to align

### ISSUE THREAD

**Issue by gcb** [gelstudios/gitfiti#49]
This is how `oneup` looks for me on my github enterprise account. Pretty much everything is default (just pressed return for offset, etc)

![screen shot 2017-06-26 at 10 58 03](https://user-images.githubusercontent.com/56283/27553154-b2cf75ca-5a5e-11e7-824a-33e7094381e5.png)

Any ideas what i am doing wrong? I am using latest commit 9feaf24

Is this because enterprise might use a different timezone?

I tried to change the oneup template to debug what is appearing where, and used:
```
  [4,4,4,4,4,4,4,4,4],
  [4,0,0,0,0,0,0,0,4],
  [4,0,0,0,0,0,0,0,4],
  [4,0,0,3,3,0,0,0,4],
  [4,0,0,3,3,0,0,0,4],
  [4,0,0,0,0,0,0,0,4],
  [4,4,4,4,4,4,4,4,4],
```

And this is what i get:
![screen shot 2017-06-26 at 11 23 42](https://user-images.githubusercontent.com/56283/27554026-f4e07290-5a61-11e7-8ede-90790967fb94.png)

Thanks!

**Comment by gelstudios** [comment]
Strange, in the first example, it looks like only the right half of `oneup` was drawn.

In the second image, it looks like you're missing the three columns left of the `3,3` blocks.

Based on the shapes being correct, I do not think this a bug. But might be an optimization GH does with commits close to the end of the calendar.

I would try using an offset of 4 to see if that helps.

Depending on what version of enterprise you are using, there should be a button in your profile to rebuild the contributions data.

**Comment by gcb** [comment]
tried offset of 15, same thing happened, but moved to the right.

**Comment by gcb** [comment]
Wondering if i am missing on the code any place where it tries to get info from github. Since mine is on enterprise, i commented out most of that code. and just return a fixed integer for my max number of commits.

**Comment by gcb** [comment]
Tried here too to rule out anything strange from enterprise github.

It simply cuts all commits from a few months. On the repo i can clearly see commits on, say, 2016-09-29. Dozens of them. But on the profile page, that day shows up empty. Even if i click that day it will say "no commits". So i guess it is github that doesn't want to play nice anymore with this.

**Comment by gelstudios** [comment]
There was a change in #42 that removed a line and added an "allow empty" argument to git, do you want to try a revision before that changed? or you can edit the lines starting around ~286 ish ?

**Comment by mytopdog** [comment]
Close issues smh

**Comment by gcb** [comment]
tried this again. still no luck. even with new repos. will try on open github and see if things change or not later. but on GH enterprise it does not align no matter what.

writting this off as some performance tweak on my GHE instance that messes up with the image by cutting some process short.
