### ISSUE TITLE
chmod +x gitfiti.sh

### ISSUE THREAD

**Issue by veggiedefender** [gelstudios/gitfiti#56]
The generated `gitfiti.sh` isn't executable right off the bat, and the user must `chmod +x` it to be able to run it. Is this intentional? I'd love to contribute a PR to automatically do that if you're okay with it.

P.S. this little tool is dope. I made some [gliders](https://github.com/veggiedefender/gliders) on my profile!

**Comment by gelstudios** [comment]
The lack of `-x` on that script was an oversight on my part, and also noticed its not even mentioned in the instructions. I probably assumed people would _know_ to do that, but it better to be inclusive about toys like this 👍 

also, I really like the gliders 👾! Please make sure your include those in your PR as well.
