### ISSUE TITLE
Text + Drawing on git board solution

### ISSUE THREAD

**Issue by jamesjarvis** [gelstudios/gitfiti#67]
A little while ago, I wrote a very similar service to this, which has a board in the same way, except you can choose to write text, or draw on it, or both. Also you can "weight" the git commits based on how active your current board is (so it doesn't show up too pale in your actual git board).

Link:
https://jamesjarvis.github.io/git-art/

Github:
https://github.com/jamesjarvis/git-art

Let me know if you have any opinions of how it can be improved!

**Comment by peymanmajidi** [comment]
Greatjob

**Comment by gelstudios** [comment]
Cool, the UI is really nice! were you inspired by gitfiti? 

One thing to note, your tool's weights do not take exisiting commits into consideration. So the color intensity of a user's calendar may not match up to the expected color.
