### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by alexjshepler** [gelstudios/gitfiti#95]
Could you please include some examples? The readme isn't the most clear and neither is the the wizard either. Its not the worst but I personally think that it could be improved.

(Low importance)

**Comment by Necione** [comment]
@alexjshepler try using this
https://codepen.io/ZachSaucier/full/PzVRBy

**Comment by gelstudios** [comment]
@alexjshepler im going to assume you figured this out... otherwise run the script and follow the prompts, then run the generated shell script
